// src/layouts/MainLayout.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { RouterView, useRoute } from 'vue-router'
import Navbar from '@/components/Navbar.vue'
import Footer from '@/components/Footer.vue'
import {
  LayoutDashboard,
  Users,
  Building2,
  TrendingUp,
  CheckSquare,
  BarChart3,
  Settings,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  CreditCard
} from 'lucide-vue-next'

const route = useRoute()
const sidebarOpen = ref(true)
const isMobile = ref(false)

const navigation = [
  { name: 'Dashboard', 
  path: '/dashboard', icon: LayoutDashboard },

  { name: 'Contacts', 
  path: '/contacts', icon: Users },

  { name: 'Companies', 
  path: '/companies', icon: Building2 },

  { name: 'Deals', 
  path: '/deals', icon: TrendingUp },

  { name: 'Tasks', 
  path: '/tasks', icon: CheckSquare },

  { name: 'Reports', 
  path: '/reports', icon: BarChart3 },

  { name: 'Billing', 
  path: '/billing', icon: CreditCard },

  { name: 'Settings', 
  path: '/settings', icon: Settings },

  { name: 'Docs', path: 
  '/docs', icon: BookOpen }
]

const checkMobile = () => {
  isMobile.value = window.innerWidth < 1024
  if (isMobile.value) {
    sidebarOpen.value = false
  } else {
    sidebarOpen.value = true
  }
}

const toggleSidebar = () => {
  sidebarOpen.value = !sidebarOpen.value
}

const closeSidebarOnMobile = () => {
  if (isMobile.value) {
    sidebarOpen.value = false
  }
}

onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
})

onUnmounted(() => {
  window.removeEventListener('resize', checkMobile)
})
</script>

<template>
  <div class="flex h-screen bg-background">
    <div v-if="sidebarOpen && isMobile" @click="closeSidebarOnMobile" class="fixed inset-0 bg-black/50 z-40 lg:hidden">
    </div>

    <aside :class="[
      'bg-card border-r transition-all duration-300 flex flex-col fixed lg:relative h-full z-50 overflow-hidden',
      isMobile ? (sidebarOpen ? 'w-64' : 'w-0') : (sidebarOpen ? 'w-64' : 'w-16'),
      isMobile && !sidebarOpen ? '-translate-x-full' : 'translate-x-0'
    ]">
      <div class="p-4 border-b flex items-center justify-between">
        <h3 v-if="sidebarOpen" class="text-sm font-semibold">Loundry Qucuci</h3>
        <button @click="toggleSidebar" class="p-2 hover:bg-accent rounded-md hidden lg:block"
          :class="{ 'mx-auto': !sidebarOpen }">
          <ChevronRight v-if="!sidebarOpen" :size="20" />
          <ChevronLeft v-else :size="20" />
        </button>
      </div>

      <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
        <router-link v-for="item in navigation" :key="item.path" :to="item.path" @click="closeSidebarOnMobile" :class="[
          'flex items-center gap-2 px-3 py-2 rounded-lg transition-colors text-sm',
          route.path === item.path
            ? 'bg-primary text-primary-foreground'
            : 'hover:bg-accent hover:text-accent-foreground'
        ]">
          <component :is="item.icon" :size="20" />
          <span v-if="sidebarOpen">{{ item.name }}</span>
        </router-link>
      </nav>
    </aside>

    <div class="flex-1 flex flex-col overflow-hidden">
      <Navbar :on-toggle-sidebar="toggleSidebar" />

      <main class="flex-1 overflow-auto">
        <div class="p-4 md:p-8">
          <RouterView />
        </div>
      </main>

      <Footer />
    </div>
  </div>
</template>

// src/layouts/MainLayout.tsx
import { useEffect, useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { NavLink, Outlet, useLocation } from "react-router-dom";
import {
  BarChart3,
  BookOpen,
  Building2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  LayoutDashboard,
  Settings,
  TrendingUp,
  Users,
} from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer.jsx";
import { ROUTES } from "@/router/paths";
import { cn } from "@/lib/utils.js";

type NavItem = {
  name: string;
  path: string;
  icon: LucideIcon;
};

/**
 * Layout utama aplikasi (sidebar + navbar + footer).
 * NavLink memakai segment awal agar nested route tetap aktif (mis. /dashboard/analytics).
 */
export function MainLayout() {
  const location = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  const navigation = useMemo<NavItem[]>(
    () => [
      { name: "Dashboard", path: ROUTES.DASHBOARD, icon: LayoutDashboard },
      { name: "Contacts", path: ROUTES.CONTACTS, icon: Users },
      { name: "Companies", path: ROUTES.COMPANIES, icon: Building2 },
      { name: "Deals", path: ROUTES.DEALS, icon: TrendingUp },
      { name: "Tasks", path: ROUTES.TASKS, icon: CheckSquare },
      { name: "Reports", path: ROUTES.REPORTS, icon: BarChart3 },
      { name: "Billing", path: ROUTES.BILLING, icon: CreditCard },
      { name: "Settings", path: ROUTES.SETTINGS, icon: Settings },
      { name: "Docs", path: ROUTES.DOCS, icon: BookOpen },
    ],
    []
  );

  useEffect(() => {
    function checkMobile() {
      const mobile = window.innerWidth < 1024;
      setIsMobile(mobile);
      setSidebarOpen(!mobile);
    }
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const toggleSidebar = () => setSidebarOpen((v) => !v);
  const closeSidebarOnMobile = () => {
    if (isMobile) setSidebarOpen(false);
  };

  function navIsActive(itemPath: string): boolean {
    if (itemPath === ROUTES.DASHBOARD) {
      return location.pathname.startsWith(ROUTES.DASHBOARD);
    }
    if (itemPath === ROUTES.SETTINGS) {
      return location.pathname.startsWith(ROUTES.SETTINGS);
    }
    if (itemPath === ROUTES.CONTACTS) {
      return location.pathname.startsWith(ROUTES.CONTACTS);
    }
    return location.pathname === itemPath;
  }

  return (
    <div className="flex h-screen bg-background">
      {sidebarOpen && isMobile ? (
        <div
          onClick={closeSidebarOnMobile}
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          aria-hidden
        />
      ) : null}

      <aside
        className={cn(
          "bg-card border-r transition-all duration-300 flex flex-col fixed lg:relative h-full z-50 overflow-hidden",
          isMobile ? (sidebarOpen ? "w-64" : "w-0") : sidebarOpen ? "w-64" : "w-16",
          isMobile && !sidebarOpen ? "-translate-x-full" : "translate-x-0"
        )}
      >
        <div className="p-4 border-b flex items-center justify-between">
          {sidebarOpen ? (
            <h3 className="text-sm font-semibold tracking-tight text-primary">
              Laundry Qucuci
            </h3>
          ) : null}

          <button
            onClick={toggleSidebar}
            className={cn(
              "p-2 hover:bg-accent rounded-md hidden lg:block",
              !sidebarOpen ? "mx-auto" : ""
            )}
            type="button"
            aria-label="Toggle sidebar width"
          >
            {!sidebarOpen ? <ChevronRight size={20} /> : <ChevronLeft size={20} />}
          </button>
        </div>

        <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
          {navigation.map((item) => {
            const Icon = item.icon;
            const active = navIsActive(item.path);
            return (
              <NavLink
                key={item.path}
                to={item.path}
                onClick={closeSidebarOnMobile}
                className={cn(
                  "flex items-center gap-2 px-3 py-2 rounded-lg transition-colors text-sm",
                  active
                    ? "bg-primary text-primary-foreground"
                    : "hover:bg-accent hover:text-accent-foreground"
                )}
              >
                <Icon size={20} />
                {sidebarOpen ? <span>{item.name}</span> : null}
              </NavLink>
            );
          })}
        </nav>
      </aside>

      <div className="flex-1 flex flex-col overflow-hidden">
        <Navbar onToggleSidebar={toggleSidebar} />

        <main className="flex-1 overflow-auto">
          <div className="p-4 md:p-8">
            <Outlet />
          </div>
        </main>

        <Footer />
      </div>
    </div>
  );
}
