// src/layouts/MainLayout.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { RouterView, useRoute } from 'vue-router'
import Navbar from '@/components/Navbar.vue'
import Footer from '@/components/Footer.vue'
import {
  LayoutDashboard,
  Users,
  Building2,
  TrendingUp,
  CheckSquare,
  BarChart3,
  Settings,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  CreditCard
} from 'lucide-vue-next'

const route = useRoute()
const sidebarOpen = ref(true)
const isMobile = ref(false)

const navigation = [
  { name: 'Dashboard', 
  path: '/dashboard', icon: LayoutDashboard },

  { name: 'Contacts', 
  path: '/contacts', icon: Users },

  { name: 'Companies', 
  path: '/companies', icon: Building2 },

  { name: 'Deals', 
  path: '/deals', icon: TrendingUp },

  { name: 'Tasks', 
  path: '/tasks', icon: CheckSquare },

  { name: 'Reports', 
  path: '/reports', icon: BarChart3 },

  { name: 'Billing', 
  path: '/billing', icon: CreditCard },

  { name: 'Settings', 
  path: '/settings', icon: Settings },

  { name: 'Docs', path: 
  '/docs', icon: BookOpen }
]

const checkMobile = () => {
  isMobile.value = window.innerWidth < 1024
  if (isMobile.value) {
    sidebarOpen.value = false
  } else {
    sidebarOpen.value = true
  }
}

const toggleSidebar = () => {
  sidebarOpen.value = !sidebarOpen.value
}

const closeSidebarOnMobile = () => {
  if (isMobile.value) {
    sidebarOpen.value = false
  }
}

onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
})

onUnmounted(() => {
  window.removeEventListener('resize', checkMobile)
})
</script>

<template>
  <div class="flex h-screen bg-background">
    <div v-if="sidebarOpen && isMobile" @click="closeSidebarOnMobile" class="fixed inset-0 bg-black/50 z-40 lg:hidden">
    </div>

    <aside :class="[
      'bg-card border-r transition-all duration-300 flex flex-col fixed lg:relative h-full z-50 overflow-hidden',
      isMobile ? (sidebarOpen ? 'w-64' : 'w-0') : (sidebarOpen ? 'w-64' : 'w-16'),
      isMobile && !sidebarOpen ? '-translate-x-full' : 'translate-x-0'
    ]">
      <div class="p-4 border-b flex items-center justify-between">
        <h3 v-if="sidebarOpen" class="text-sm font-semibold">Loundry Qucuci</h3>
        <button @click="toggleSidebar" class="p-2 hover:bg-accent rounded-md hidden lg:block"
          :class="{ 'mx-auto': !sidebarOpen }">
          <ChevronRight v-if="!sidebarOpen" :size="20" />
          <ChevronLeft v-else :size="20" />
        </button>
      </div>

      <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
        <router-link v-for="item in navigation" :key="item.path" :to="item.path" @click="closeSidebarOnMobile" :class="[
          'flex items-center gap-2 px-3 py-2 rounded-lg transition-colors text-sm',
          route.path === item.path
            ? 'bg-primary text-primary-foreground'
            : 'hover:bg-accent hover:text-accent-foreground'
        ]">
          <component :is="item.icon" :size="20" />
          <span v-if="sidebarOpen">{{ item.name }}</span>
        </router-link>
      </nav>
    </aside>

    <div class="flex-1 flex flex-col overflow-hidden">
      <Navbar :on-toggle-sidebar="toggleSidebar" />

      <main class="flex-1 overflow-auto">
        <div class="p-4 md:p-8">
          <RouterView />
        </div>
      </main>

      <Footer />
    </div>
  </div>
</template>

// src/layouts/MainLayout.jsx
import { useEffect, useMemo, useState } from "react";
import { NavLink, Outlet, useLocation } from "react-router-dom";

import {
  BarChart3,
  BookOpen,
  Building2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  LayoutDashboard,
  Settings,
  Users,
  Sparkles,
} from "lucide-react";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer.jsx";
import { ROUTES } from "@/router/paths";
import { cn } from "@/lib/utils.js";

export function MainLayout() {

  const location = useLocation();

  const [sidebarOpen,setSidebarOpen] = useState(true);

  const [isMobile,setIsMobile] = useState(false);

  const navigation = useMemo(() => [

    {
      name:"Dashboard",
      path:ROUTES.DASHBOARD,
      icon:LayoutDashboard
    },

      {
    name:"Pelanggan",
    path:"/customers",
    icon:Users
  },

    {
      name:"Laundry",
      path:ROUTES.COMPANIES,
      icon:Building2
    },

    {
      name:"Pesanan",
      path:ROUTES.TASKS,
      icon:CheckSquare
    },

    {
      name:"Laporan",
      path:ROUTES.REPORTS,
      icon:BarChart3
    },

    {
      name:"Dokumentasi",
      path:ROUTES.DOCS,
      icon:BookOpen
    },

    {
      name:"Pengaturan",
      path:ROUTES.SETTINGS,
      icon:Settings
    }

  ],[]);

  useEffect(()=>{

    function checkMobile(){

      const mobile = window.innerWidth < 1024;

      setIsMobile(mobile);

      setSidebarOpen(!mobile);

    }

    checkMobile();

    window.addEventListener(
      "resize",
      checkMobile
    );

    return ()=>{

      window.removeEventListener(
        "resize",
        checkMobile
      );

    };

  },[]);

  function navIsActive(path){

    return location.pathname.startsWith(path);

  }

  return (

    <div
      className="
      flex
      h-screen
      bg-gradient-to-br
      from-sky-100
      via-cyan-50
      to-blue-100
      "
    >

      <aside

        className={cn(

          `
          transition-all
          duration-300
          shadow-2xl
          backdrop-blur-lg
          bg-white/80
          border-r
          border-white/30
          flex
          flex-col
          overflow-hidden
          `,

          sidebarOpen
          ? "w-64"
          : "w-20"

        )}

      >

        {/* Logo */}

        <div
          className="
          p-5
          border-b
          flex
          items-center
          justify-between
          "
        >

          {sidebarOpen && (

            <div
              className="
              flex
              items-center
              gap-2
              "
            >

              <Sparkles
                className="
                text-cyan-500
                "
              />

              <h1
                className="
                font-bold
                text-xl
                bg-gradient-to-r
                from-blue-600
                to-cyan-500
                bg-clip-text
                text-transparent
                "
              >

                LaundryQ

              </h1>

            </div>

          )}

          <button

            onClick={()=>
              setSidebarOpen(
                !sidebarOpen
              )
            }

            className="
            p-2
            rounded-lg
            hover:bg-cyan-100
            transition
            "

          >

            {

              sidebarOpen

              ?

              <ChevronLeft/>

              :

              <ChevronRight/>

            }

          </button>

        </div>


        {/* Menu */}

        <nav
          className="
          flex-1
          p-3
          space-y-2
          "
        >

          {

            navigation.map(item=>{

              const Icon = item.icon;

              const active =
              navIsActive(item.path);

              return(

                <NavLink

                  key={item.path}

                  to={item.path}

                  className={cn(

                    `
                    flex
                    items-center
                    gap-3
                    px-4
                    py-3
                    rounded-xl
                    transition-all
                    duration-300
                    group
                    `,

                    active

                    ?

                    `
                    bg-gradient-to-r
                    from-cyan-500
                    to-blue-500
                    text-white
                    shadow-lg
                    scale-105
                    `

                    :

                    `
                    hover:bg-cyan-100
                    hover:translate-x-2
                    hover:shadow-md
                    `

                  )}

                >

                  <Icon

                    size={20}

                    className="
                    group-hover:rotate-12
                    transition-transform
                    "
                  />

                  {

                    sidebarOpen &&

                    <span>

                      {item.name}

                    </span>

                  }

                </NavLink>

              );

            })

          }

        </nav>

      </aside>


      {/* Content */}

      <div
        className="
        flex-1
        flex
        flex-col
        overflow-hidden
        "
      >

        <Navbar
          onToggleSidebar={
            ()=>setSidebarOpen(
              !sidebarOpen
            )
          }
        />

        <main
          className="
          flex-1
          overflow-auto
          p-6
          "
        >

          <Outlet/>

        </main>

        <Footer/>

      </div>

    </div>

  );

}
